name: Audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs: 
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify Dependencies
      run: go mod verify    

    - name: Run go vet
      run: go vet ./...  

    - name: Install staticchek
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...  

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint  
      run: golint ./...

    - name: Run tests
      run: go test -race -vet=off ./...  

    - name: Unit tests
      run: | 
            go test ./... -coverprofile coverage.out -covermode count
            go tool cover -func coverage.out   

    - name: Covergae Gate 
      env:
          COVERAGE_THRESHOLD: 0
      run: |
            echo "Checking if the coverage is about the threshold or not"
            echo "Current Threshold : $COVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $COVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi
            
    - name: Build
      run: go build -o dockerhub-go
